"""users now have name instead of username and name is not unique

Revision ID: 2ce03cb020b0
Revises: 5ef63cf94650
Create Date: 2025-06-22 13:42:50.408950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce03cb020b0'
down_revision = '5ef63cf94650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
