"""creates the book entity

Revision ID: 5ef63cf94650
Revises: 48d67d342fa3
Create Date: 2025-06-22 09:45:34.522091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef63cf94650'
down_revision = '48d67d342fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=120), nullable=False),
    sa.Column('publisher', sa.String(length=120), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('new', 'used', 'semi_new', name='book_status'), nullable=False),
    sa.Column('donated', sa.Boolean(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
